# Physical parameters

offsets:
  shoulder_offset: 0.120 # measured from model
  elbow_offset: 0.027 # measured from model

inertia_parameters:
  base_mass: 2.0  # This mass might be incorrect
  shoulder_mass: 1.98
  upper_arm_mass: 3.4445
  forearm_mass: 1.437
  wrist_1_mass: 0.871
  wrist_2_mass: 0.805
  wrist_3_mass: 0.261

  shoulder_radius: 0.060   # manually measured
  upper_arm_radius: 0.054  # manually measured
  elbow_radius: 0.060      # manually measured
  forearm_radius: 0.040    # manually measured
  wrist_radius: 0.045      # manually measured

  links:
    base:
      radius: 0.075
      length: 0.038

  # model referring to https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/
  center_of_mass:
    shoulder_cog:
      x: 0.0        # model.x
      y: 0.0        # -model.z
      z: -0.02      # model.y
    upper_arm_cog:
      x: -0.11355   # model.x - upper_arm_length
      y: 0.0        # model.y
      z: 0.1157     # model.z
    forearm_cog:
      x: -0.1632    # model.x - forearm_length
      y: 0.0        # model.y
      z: 0.0238     # model.z
    wrist_1_cog:
      x: 0.0        # model.x
      y: -0.01      # -model.z
      z: 0.0        # model.y
    wrist_2_cog:
      x: 0.0        # model.x
      y: 0.01       # model.z
      z: 0.0        # -model.y
    wrist_3_cog:
      x: 0.0        # model.x
      y: 0.0        # model.y
      z: -0.02      # model.z

  # compatible with cylinder approximation
  rotation:
    shoulder:
      roll: 0
      pitch: 0
      yaw: 0
    upper_arm:
      roll: 0
      pitch: 1.570796326794897
      yaw: 0
    forearm:
      roll: 0
      pitch: 1.570796326794897
      yaw: 0
    wrist_1:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_2:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_3:
      roll: 0
      pitch: 0
      yaw: 0

  # generated using cylinder approximation
  tensor:
    shoulder:
      ixx: 0.008093166666666665
      ixy: 0
      ixz: 0
      iyy: 0.008093166666666665
      iyz: 0
      izz: 0.005625
    upper_arm:
      ixx: 0.021728491912499998
      ixy: 0
      ixz: 0
      iyy: 0.021728491912499998
      iyz: 0
      izz: 0.00961875
    forearm:
      ixx: 0.006544570199999999
      ixy: 0
      ixz: 0
      iyy: 0.006544570199999999
      iyz: 0
      izz: 0.00354375
    wrist_1:
      ixx: 0.0020849999999999996
      ixy: 0
      ixz: 0
      iyy: 0.0020849999999999996
      iyz: 0
      izz: 0.00225
    wrist_2:
      ixx: 0.0020849999999999996
      ixy: 0
      ixz: 0
      iyy: 0.0020849999999999996
      iyz: 0
      izz: 0.00225
    wrist_3:
      ixx: 0.00013626666666666665
      ixy: 0
      ixz: 0
      iyy: 0.00013626666666666665
      iyz: 0
      izz: 0.0001792
